const actionTypes = {
  SET_ITEMS: 'SET_ITEMS',
  SET_SEARCH: 'SET_SEARCH',
  SET_FILTERS: 'SET_FILTERS',
  CLICK_FILTER: 'CLICK_FILTER',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  UPDATE_DELIVERY_INFO: 'UPDATE_DELIVERY_INFO',
  CLEAR_CART: 'CLEAR_CART', // TODO
  CLEAR_FILTERS: 'CLEAR_FILTERS', // TODO
  CLEAR_DELIVERY_INFO: 'CLEAR_DELIVERY_INFO', // TODO
};

export default actionTypes;
